services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-shm-db
    ports:
      - "11521:1521"
      - "15500:5500"
    environment:
      - ORACLE_PASSWORD=Admin123
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./db:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  oracle_data:
    name: oracle_shm_data
